import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Wallet } from './Wallet'
import { Provider } from 'jotai'
import Jotai from './Jotai'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Jotai>
          <Wallet>
            {children}
          </Wallet>
        </Jotai>
      </body>
    </html>
  )
}
